< Primordial, Ljava/io/BufferedWriter, <clinit>()V > 86
< Primordial, Ljava/util/ArrayList, toArray([Ljava/lang/Object;)[Ljava/lang/Object; > 201
< Primordial, Ljava/io/PrintStream, newLine()V > 139
< Primordial, Ljava/lang/StackTraceElement, equals(Ljava/lang/Object;)Z > 180
< Primordial, Ljava/util/Hashtable$EmptyEnumerator, <init>()V > 54
< Primordial, Ljava/security/Policy, <clinit>()V > 108
< Primordial, Ljava/lang/Integer, <clinit>()V > 129
< Primordial, Ljava/io/PrintStream, print(Ljava/lang/Object;)V > 138
< Primordial, Ljava/lang/Thread, interrupt0()V > 156
< Primordial, Ljava/io/File, getCanonicalPath()Ljava/lang/String; > 219
< Primordial, Ljava/lang/StringIndexOutOfBoundsException, <init>(I)V > 124
< Primordial, Ljava/io/FileInputStream, read([B)I > 9
< Primordial, Ljava/lang/IllegalArgumentException, <init>(Ljava/lang/String;)V > 100
< Primordial, Ljava/util/ArrayList, <init>(I)V > 197
< Primordial, Ljava/security/AccessControlContext, optimize()Ljava/security/AccessControlContext; > 164
< Primordial, Ljava/lang/System, getSecurityManager()Ljava/lang/SecurityManager; > 29
< Primordial, Ljava/lang/Thread, dumpStack()V > 92
< Primordial, Ljava/security/BasicPermission, init(Ljava/lang/String;)V > 97
< Primordial, Ljava/lang/Throwable, toString()Ljava/lang/String; > 162
< Primordial, Ljava/io/File, <init>(Ljava/lang/String;)V > 13
< Primordial, Ljava/io/PrintStream, <init>(ZLjava/io/OutputStream;)V > 72
< Primordial, Ljava/lang/AbstractStringBuilder, append(I)Ljava/lang/AbstractStringBuilder; > 116
< Primordial, Ljava/lang/StringBuilder, append(Ljava/lang/String;)Ljava/lang/AbstractStringBuilder; > 126
< Primordial, Ljava/io/PrintStream, print(I)V > 189
< Primordial, Ljava/lang/StringBuilder, append(Ljava/lang/String;)Ljava/lang/StringBuilder; > 112
< Primordial, Ljava/io/FileDescriptor, <clinit>()V > 30
< Primordial, Ljava/lang/AbstractStringBuilder, stringSizeOfInt(I)I > 127
< Primordial, Ljava/io/FileSystem$1, <init>()V > 46
< Primordial, Ljava/lang/SecurityManager, <clinit>()V > 16
< Primordial, Ljava/lang/Class, getClassLoader0()Ljava/lang/ClassLoader; > 61
< Primordial, Ljava/io/PrintStream, <init>(Ljava/io/OutputStream;)V > 41
< Primordial, Ljava/lang/String, <init>([CII)V > 131
< Primordial, Ljava/lang/Class, getComponentType()Ljava/lang/Class; > 207
< Primordial, Ljava/io/OutputStreamWriter, <init>(Ljava/io/OutputStream;)V > 73
< Primordial, Ljava/security/Policy, isSet()Z > 107
< Primordial, Ljava/lang/Throwable, <init>()V > 80
< Primordial, Ljava/io/PrintStream, println(Ljava/lang/String;)V > 134
< Primordial, Ljava/io/FileSystem$1, getSeparator()C > 174
< Primordial, Ljava/util/ArrayList, add(Ljava/lang/Object;)Z > 199
< Primordial, Ljava/lang/String, indexOf(II)I > 158
< Primordial, Ljava/io/FileInputStream, open(Ljava/lang/String;)V > 32
< Primordial, Ljava/lang/reflect/Array, newInstance(Ljava/lang/Class;I)Ljava/lang/Object; > 208
< Primordial, Ljava/lang/System, arraycopy([Ljava/lang/Object;I[Ljava/lang/Object;II)V > 183
< Primordial, Ljava/lang/String$CaseInsensitiveComparator, <init>()V > 11
< Primordial, Ljava/io/FileSystem, getFileSystem()Ljava/io/FileSystem; > 21
< Primordial, Ljava/util/AbstractList, <init>()V > 119
< Primordial, Ljava/io/FileSystem$1, normalize(Ljava/lang/String;)Ljava/lang/String; > 172
< Primordial, Ljava/io/FilePermission, access$0(Ljava/io/FilePermission;)Ljava/lang/String; > 218
< Primordial, Lcom/ibm/wala/FakeRootClass, fakeRootMethod()V > 0
< Primordial, Ljava/lang/String, toString()Ljava/lang/String; > 217
< Primordial, Ljava/lang/AbstractStringBuilder, <init>(I)V > 48
< Primordial, Ljava/io/FilePermission$1, <init>(Ljava/io/FilePermission;)V > 203
< Primordial, Ljava/io/OutputStreamWriter, flushBuffer()V > 147
< Primordial, Ljava/lang/String, lastIndexOf(Ljava/lang/String;)I > 186
< Primordial, Ljava/io/Writer, <init>(Ljava/lang/Object;)V > 85
< Primordial, Ljava/util/Vector, <init>()V > 75
< Primordial, Ljava/util/Vector, <init>(I)V > 88
< Primordial, Ljava/io/BufferedWriter, ensureOpen()V > 153
< Primordial, Ljava/io/FileOutputStream, open(Ljava/lang/String;)V > 35
< Primordial, Ljava/lang/AbstractStringBuilder, append(Ljava/lang/String;)Ljava/lang/AbstractStringBuilder; > 123
< Primordial, Ljava/lang/Throwable, fillInStackTrace()Ljava/lang/Throwable; > 95
< Primordial, Ljava/lang/ClassLoader, desiredAssertionStatus(Ljava/lang/String;)Z > 168
< Primordial, Ljava/lang/String, lastIndexOf(Ljava/lang/String;I)I > 187
< Primordial, Ljava/io/FileOutputStream, openAppend(Ljava/lang/String;)V > 34
< Primordial, Ljava/security/AccessControlException, <init>(Ljava/lang/String;Ljava/security/Permission;)V > 222
< Primordial, Ljava/lang/System, <clinit>()V > 8
< Primordial, Ljava/lang/Throwable, <init>(Ljava/lang/String;)V > 121
< Primordial, Ljava/util/ArrayList, indexOf(Ljava/lang/Object;)I > 205
< Primordial, Ljava/io/FileInputStream, <init>(Ljava/io/File;)V > 14
< Primordial, Ljava/io/PrintStream, print(Ljava/lang/String;)V > 142
< Primordial, Ljava/io/PrintStream, println(Ljava/lang/Object;)V > 132
< Primordial, Ljava/lang/String$CaseInsensitiveComparator, <init>(Ljava/lang/String$CaseInsensitiveComparator;)V > 5
< Primordial, Ljava/lang/RuntimePermission, <init>(Ljava/lang/String;)V > 70
< Primordial, Ljava/util/Hashtable, put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; > 40
< Primordial, Ljava/lang/System, getProperty(Ljava/lang/String;)Ljava/lang/String; > 67
< Primordial, Ljava/io/PrintStream, init(Ljava/io/OutputStreamWriter;)V > 74
< Primordial, Ljava/io/OutputStream, flush()V > 148
< Primordial, Ljava/io/BufferedWriter, min(II)I > 160
< Primordial, Ljava/lang/SecurityManager, checkWrite(Ljava/lang/String;)V > 169
< Primordial, Ljava/lang/String, <init>(II[C)V > 212
< Primordial, Ljava/lang/StringBuilder, append(Ljava/lang/Object;)Ljava/lang/StringBuilder; > 94
< Primordial, Ljava/security/AccessController, getInheritedAccessControlContext()Ljava/security/AccessControlContext; > 181
< Primordial, Ljava/util/ArrayList, contains(Ljava/lang/Object;)Z > 198
< Primordial, Ljava/util/Hashtable, <init>()V > 71
< Primordial, Ljava/util/AbstractCollection, <init>()V > 130
< Primordial, Ljava/io/FileSystem$1, resolve(Ljava/io/File;)Ljava/lang/String; > 224
< Primordial, Ljava/lang/StringBuilder, append(F)Ljava/lang/StringBuilder; > 103
< Primordial, Ljava/lang/RuntimeException, <init>(Ljava/lang/String;)V > 104
< Primordial, Ljava/lang/AbstractStringBuilder, append(C)Ljava/lang/AbstractStringBuilder; > 49
< Primordial, Ljava/lang/System, arraycopy([CI[CII)V > 79
< Primordial, Ljava/security/AccessController, checkPermission(Ljava/security/Permission;)V > 77
< Primordial, Ljava/lang/Integer, toString(I)Ljava/lang/String; > 209
< Primordial, Ljava/security/AccessControlContext, checkPermission(Ljava/security/Permission;)V > 215
< Primordial, Ljava/lang/Class, desiredAssertionStatus()Z > 20
< Primordial, Ljava/lang/String, equalsIgnoreCase(Ljava/lang/String;)Z > 165
< Primordial, Ljava/io/FileInputStream, read()I > 176
< Primordial, Ljava/lang/SecurityManager, checkAccess(Ljava/lang/Thread;)V > 159
< Primordial, Ljava/lang/System, initializeSystemClass()V > 17
< Primordial, Ljava/util/Hashtable, <clinit>()V > 38
< Primordial, Ljava/io/BufferedWriter, newLine()V > 145
< Primordial, Ljava/lang/SecurityManager, checkRead(Ljava/lang/String;)V > 170
< Primordial, Ljava/io/FilePermission, init(I)V > 194
< Primordial, Ljava/security/AccessControlContext$1, <init>(Ljava/security/AccessControlContext;Lsun/security/util/Debug;Ljava/security/ProtectionDomain;)V > 221
< Primordial, Ljava/io/File, <clinit>()V > 12
< Primordial, Ljava/lang/String, <clinit>()V > 2
< Primordial, Ljava/lang/String, substring(II)Ljava/lang/String; > 115
< Primordial, Ljava/lang/Throwable, getOurStackTrace()[Ljava/lang/StackTraceElement; > 133
< Primordial, Ljava/io/FilePermission, access$1(Ljava/io/FilePermission;)Z > 220
< Primordial, Ljava/lang/RuntimeException, <init>()V > 50
< Primordial, Ljava/io/IOException, <init>(Ljava/lang/String;)V > 152
< Primordial, Ljava/security/AccessController, doPrivileged(Ljava/security/PrivilegedAction;)Ljava/lang/Object; > 78
< Primordial, Ljava/security/BasicPermission, <init>(Ljava/lang/String;)V > 81
< Primordial, Ljava/util/Vector, <init>(II)V > 106
< Primordial, Ljava/lang/ClassLoader, isAncestor(Ljava/lang/ClassLoader;)Z > 167
< Primordial, Ljava/lang/Throwable, getLocalizedMessage()Ljava/lang/String; > 179
< Primordial, Ljava/io/FilePermission, getActions()Ljava/lang/String; > 223
< Primordial, Ljava/lang/String, length()I > 111
< Primordial, Ljava/lang/Class, <clinit>()V > 44
< Primordial, Ljava/lang/Throwable, printStackTrace(Ljava/io/PrintStream;)V > 122
< Primordial, Ljava/lang/StringBuilder, <init>()V > 24
< Primordial, Ljava/io/FileDescriptor, <init>(I)V > 51
< Primordial, Ljava/lang/String, hashCode()I > 57
< Primordial, Ljava/lang/Class, getPrimitiveClass(Ljava/lang/String;)Ljava/lang/Class; > 117
< Primordial, Ljava/security/AccessControlContext$1, run()Ljava/lang/Object; > 228
< Primordial, Ljava/util/Dictionary, <init>()V > 98
< Primordial, Ljava/lang/StringBuilder, append(I)Ljava/lang/StringBuilder; > 99
< Primordial, Ljava/lang/NullPointerException, <init>(Ljava/lang/String;)V > 84
< Primordial, Ljava/lang/Thread, <clinit>()V > 53
< Primordial, Ljava/util/Hashtable, <init>(IF)V > 82
< Primordial, Ljava/util/Properties, <init>(Ljava/util/Properties;)V > 56
< Primordial, Ljava/lang/Throwable, getStackTraceDepth()I > 140
< Primordial, Ljava/io/FileOutputStream, <init>(Ljava/io/File;Z)V > 15
< Primordial, Ljava/io/File, getPath()Ljava/lang/String; > 28
< Primordial, Ljava/lang/reflect/Array, newArray(Ljava/lang/Class;I)Ljava/lang/Object; > 210
< Primordial, Ljava/io/FileDescriptor, <init>()V > 31
< Primordial, Ljava/io/FileSystem$1, prefixLength(Ljava/lang/String;)I > 171
< Primordial, Ljava/lang/Thread, checkAccess()V > 155
< Primordial, Ljava/lang/StackTraceElement, toString()Ljava/lang/String; > 166
< Primordial, Ljava/io/ObjectStreamClass, <clinit>()V > 65
< Primordial, Ljava/io/FilterOutputStream, <init>(Ljava/io/OutputStream;)V > 83
< Primordial, Ljava/security/Permission, toString()Ljava/lang/String; > 216
< Primordial, Ljava/util/Properties, <clinit>()V > 37
< Primordial, Ljava/security/Permission, getName()Ljava/lang/String; > 202
< Primordial, Ljava/io/PrintStream, ensureOpen()V > 144
< Primordial, Ljava/util/ArrayList, size()I > 200
< Primordial, Ljava/lang/ClassLoader, <clinit>()V > 63
< Primordial, Ljava/lang/Class, desiredAssertionStatus0(Ljava/lang/Class;)Z > 43
< Primordial, Ljava/lang/String, getChars(II[CI)V > 136
< Primordial, Ljava/lang/Throwable, getStackTraceElement(I)Ljava/lang/StackTraceElement; > 141
< Primordial, Ljava/lang/Throwable, getCause()Ljava/lang/Throwable; > 135
< Primordial, Ljava/io/FileSystem, getBooleanProperty(Ljava/lang/String;Z)Z > 47
< Primordial, Ljava/io/PrintStream, write(Ljava/lang/String;)V > 143
< Primordial, Ljava/io/FileOutputStream, <init>(Ljava/lang/String;)V > 7
< Primordial, Ljava/io/BufferedWriter, flushBuffer()V > 146
< Primordial, Ljava/lang/String, valueOf(Ljava/lang/Object;)Ljava/lang/String; > 113
< Primordial, Ljava/lang/String, charAt(I)C > 114
< Primordial, Ljava/security/Permission, <init>(Ljava/lang/String;)V > 96
< Primordial, Ljava/util/Hashtable, rehash()V > 58
< Primordial, Ljava/lang/Integer, toString(II)Ljava/lang/String; > 204
< Primordial, Ljava/lang/Thread, currentThread()Ljava/lang/Thread; > 52
< Primordial, Ljava/io/FileInputStream, <init>(Ljava/lang/String;)V > 6
< Primordial, Ljava/util/Properties, <init>()V > 39
< Primordial, Ljava/lang/AbstractStringBuilder, append(F)Ljava/lang/AbstractStringBuilder; > 118
< Primordial, Ljava/io/BufferedWriter, <init>(Ljava/io/Writer;I)V > 105
< Primordial, Ljava/io/InputStream, <init>()V > 27
< Primordial, Ljava/io/Writer, write(Ljava/lang/String;)V > 150
< Primordial, Ljava/lang/AbstractStringBuilder, <clinit>()V > 23
< Primordial, Ljava/lang/Thread, interrupt()V > 149
< Primordial, Ljava/lang/StringBuilder, append(C)Ljava/lang/StringBuilder; > 25
< Primordial, Ljava/lang/Throwable, printStackTraceAsCause(Ljava/io/PrintStream;[Ljava/lang/StackTraceElement;)V > 163
< Primordial, Ljava/util/ArrayList, ensureCapacity(I)V > 206
< Primordial, Ljava/security/AccessControlContext, <clinit>()V > 91
< Primordial, Ljava/lang/AbstractStringBuilder, expandCapacity(I)V > 68
< Primordial, Ljava/io/FilePermission, <init>(Ljava/lang/String;Ljava/lang/String;)V > 188
< Primordial, Ljava/lang/Integer, stringSize(I)I > 211
< Primordial, Lcom/ibm/wala/FakeRootClass, fakeWorldClinit()V > 1
< Primordial, Ljava/io/FileSystem, <init>()V > 66
< Extension, Ltest/TestProgram, main([Ljava/lang/String;)V > 4
< Primordial, Ljava/io/FilePermission, getMask(Ljava/lang/String;)I > 193
< Primordial, Ljava/io/FileOutputStream, write([B)V > 10
< Primordial, Ljava/lang/Class, getClassLoader()Ljava/lang/ClassLoader; > 42
< Primordial, Ljava/lang/StackTraceElement, getClassName()Ljava/lang/String; > 184
< Primordial, Ljava/lang/Float, <clinit>()V > 102
< Primordial, Ljava/lang/String, indexOf(I)I > 151
< Primordial, Ljava/io/OutputStreamWriter, write([CII)V > 154
< Primordial, Ljava/lang/String, equals(Ljava/lang/Object;)Z > 177
< Primordial, Ljava/util/Hashtable$EmptyIterator, <init>()V > 55
< Primordial, Ljava/lang/Object, <init>()V > 3
< Primordial, Ljava/io/FileSystem$1, getPathSeparator()C > 173
< Primordial, Ljava/lang/Exception, <init>()V > 69
< Primordial, Ljava/lang/Exception, <init>(Ljava/lang/String;)V > 109
< Primordial, Ljava/lang/StackTraceElement, eq(Ljava/lang/Object;Ljava/lang/Object;)Z > 191
< Primordial, Ljava/io/FileOutputStream, writeBytes([BII)V > 19
< Primordial, Ljava/lang/Integer, getChars(II[C)V > 128
< Primordial, Ljava/lang/Throwable, getMessage()Ljava/lang/String; > 190
< Primordial, Ljava/io/OutputStream, <init>()V > 33
< Primordial, Ljava/security/AccessController, getStackAccessControlContext()Ljava/security/AccessControlContext; > 89
< Primordial, Ljava/io/FileSystem, <clinit>()V > 22
< Primordial, Ljava/lang/StringBuilder, toString()Ljava/lang/String; > 120
< Primordial, Ljava/lang/String, <init>(III)V > 125
< Primordial, Ljava/security/AccessControlContext, <init>([Ljava/security/ProtectionDomain;)V > 192
< Primordial, Ljava/lang/String, valueOf(I)Ljava/lang/String; > 195
< Primordial, Ljava/lang/SecurityManager, checkPermission(Ljava/security/Permission;)V > 64
< Primordial, Ljava/lang/Object, getClass()Ljava/lang/Class; > 178
< Primordial, Ljava/io/BufferedWriter, write(Ljava/lang/String;II)V > 157
< Primordial, Ljava/lang/SecurityException, <init>(Ljava/lang/String;)V > 226
< Primordial, Ljava/io/BufferedWriter, <init>(Ljava/io/Writer;)V > 87
< Primordial, Ljava/io/PrintStream, println(I)V > 175
< Primordial, Ljava/io/FilePermission$1, run()Ljava/lang/Object; > 214
< Primordial, Ljava/security/AccessControlContext, goCombiner([Ljava/security/ProtectionDomain;Ljava/security/AccessControlContext;)Ljava/security/AccessControlContext; > 182
< Primordial, Ljava/lang/Object, clone()Ljava/lang/Object; > 196
< Primordial, Ljava/lang/Float, isNaN(F)Z > 101
< Primordial, Ljava/lang/ClassLoader, getCallerClassLoader()Ljava/lang/ClassLoader; > 62
< Primordial, Ljava/lang/StringBuilder, <init>(Ljava/lang/String;)V > 93
< Primordial, Ljava/lang/IndexOutOfBoundsException, <init>(Ljava/lang/String;)V > 137
< Primordial, Ljava/lang/NullPointerException, <init>()V > 26
< Primordial, Ljava/io/FilePermission, getActions(I)Ljava/lang/String; > 227
< Primordial, Ljava/security/AccessControlContext, getDebug()Lsun/security/util/Debug; > 90
< Primordial, Ljava/lang/Thread, getThreadGroup()Ljava/lang/ThreadGroup; > 161
< Primordial, Ljava/lang/NegativeArraySizeException, <init>()V > 213
< Primordial, Ljava/util/Stack, <init>()V > 76
< Primordial, Ljava/lang/Throwable, printStackTrace()V > 110
< Primordial, Ljava/io/FileSystem$1, canonicalize(Ljava/lang/String;)Ljava/lang/String; > 225
< Primordial, Ljava/io/FileInputStream, readBytes([BII)I > 18
< Primordial, Ljava/lang/Class, getName()Ljava/lang/String; > 45
< Primordial, Ljava/lang/SecurityManager, getRootGroup()Ljava/lang/ThreadGroup; > 36
< Primordial, Ljava/util/Hashtable$Entry, <init>(ILjava/lang/Object;Ljava/lang/Object;Ljava/util/Hashtable$Entry;)V > 59
< Primordial, Ljava/lang/StackTraceElement, isNativeMethod()Z > 185
< Primordial, Ljava/io/PrintStream, <init>(Ljava/io/OutputStream;Z)V > 60
77 89 215 120 94 93 90 52 164 92
154
51 3
128
205
25 49
102 117
179 190
76 75
153 152
50 69
127
204 209 131
24 48
101
178
75 88
152 109
49 68
126 112
203 3
23
100 104
177
74 87
151 158
228 120 94 93
48 3
125 3
202
22 47
99 116
176
73 85
150 157 111
227 112 120 25 24
47 165 67
124 120 137 99 93
201 178 183 208 207
21 46
98 3
175 189 139
72 83 84
149 155 156 52
226 104
46 66
123 68 111 136
200
20 43 45 42 168
97 100 114 111 84 115
174
71 82
148
225
45
122 135 132 120 94 134 93 133 163
199 206
19
96 3
173
70 81
147
224
44
121 95 3
198 205
18
95
172
69 80
146 154 153
223 227
43
120 131
197 100 120 99 119 93
17 40 39 33 27 41
94 112 113
171
68 79
145 150
222 226
42 62 64 61 29 167
119 130
196
16 36 3
93 112 48 111
170 188 64
67
144 152
221 3
41 60
118
195 204
15 34 31 28 33 169 35 29 26
92 109 110
169 188 64
66 3
143 149 146 151 144 148 150 147 52
220
40 57 177 59 58 26
117
194 203 100 114 111 177 202 84 78 115
14 31 28 27 170 32 29 26
91
168 186 187 115
65 78
142 143
219 224 225
39 56
116 126 68 128 127
193 112 100 120 93
13 172 26 171 3
90 107
167
64 77
141
218
38 54 55
115 125 124
192 201 198 200 197 199 196 3
12 20 120 25 174 24 21 173 3
89
166 112 120 99 93 113 185 184
63 76 75
140
217
37
114 124
191
11 3
88 106
165
62
139 149 146 144 148 145 147 52
216 112 178 120 45 111 223 93
36 52 161
113 166 217 162 216
190
10 19
87 105
164 181 183 182
61
138 143 113
215 112 221 92 52 78 222 84 90 93 99 120 94
35
112 123
189 195 143
9 18
86
163 112 180 120 94 135 134 99 93 133 163
60 74 73 72
137 104
214 112 218 220 120 13 93 113 219
34
111
188 194 96 193
8 17
85 26 3
162 112 178 120 45 93 113 179
59 3
136 124
213 50
33 3
110 122
187
7 13 15
84 104
161
58
135
212 3
32
109 121
186 187
6 14 13
83 33
160
57
134 142 139
211
31 3
108
185
5 11
82 103 100 120 99 93 101 98
159 64 84 161
56 71
133 140 141
210 213 3
30 51
107
184
4 175 10 7 110 176 9 6
81 97 96
158
55 3
132 139 138
209 212 128 211
29
106 100 120 99 119 93
183
3
80 95 3
157 146 160 136 153
54 3
131 124 3
208 210
28
105 100 85
182 90
2 5
79
156
53 70
130 3
207
27 3
104 109
181 192
1 53 12 65 30 86 63 22 16 37 91 2 8 108 23 129 38 44 102
78 214 228
155 159 29
52
129 117
206 183
26 50
103 118
180 191
0 4 1 3
